In [225]:
import numpy as np
import pandas as pd

df= pd.read_csv("/content/drive/MyDrive/MayHoc/Dataset/corona_tested_individuals_ver_006/corona_tested_individuals_ver_0083.english.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [273]:
df.head(10)

test_date  cough  fever  ...  age_60_and_above  gender         test_indication
0  2020-11-12      0      0  ...                No    male                   Other
1  2020-11-12      0      1  ...                No    male                   Other
2  2020-11-12      0      0  ...               Yes  female                   Other
3  2020-11-12      0      0  ...                No    male                   Other
4  2020-11-12      0      1  ...                No    male  Contact with confirmed
5  2020-11-12      1      0  ...                No    male                   Other
6  2020-11-12      1      1  ...                No    male                   Other
7  2020-11-12      0      0  ...                No  female  Contact with confirmed
8  2020-11-12      0      0  ...                No    male                   Other
9  2020-11-12      1      1  ...                No    male                   Other

[10 rows x 10 columns]

In [227]:
#Tổng các thuộc tính của data
print('Số thuộc tính:',len(df.columns))
print('Các thuộc tính:',df.columns)

Số thuộc tính: 10
Các thuộc tính: Index(['test_date', 'cough', 'fever', 'sore_throat', 'shortness_of_breath',
       'head_ache', 'corona_result', 'age_60_and_above', 'gender',
       'test_indication'],
      dtype='object')


In [228]:
df.isnull().sum()

test_date                   0
cough                       0
fever                       0
sore_throat                 0
shortness_of_breath         0
head_ache                   0
corona_result               0
age_60_and_above       547644
gender                  92886
test_indication             0
dtype: int64

In [229]:
X_nomiss=df[['cough','fever','sore_throat','shortness_of_breath','head_ache']]
X_miss1=df['age_60_and_above']
X_miss2=df['gender']
X_encode=df['test_indication']
y=df['corona_result']

In [230]:
import pandas as pd
import numpy as np

fill_Xmiss1 = X_miss1.fillna('No')
fill_Xmiss2=X_miss2.fillna('male')

In [231]:
fill_Xmiss1.isnull().sum()
fill_Xmiss2.isnull().sum()

0

In [232]:

import pandas as pd
X_nomiss1=pd.DataFrame(fill_Xmiss1, columns = ['age_60_and_above'])
X_nomiss2=pd.DataFrame(fill_Xmiss2, columns = ['gender'])

In [292]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(X_encode)
testind_data=le.transform(X_encode)
le.inverse_transform([0,1,2])

array(['Abroad', 'Contact with confirmed', 'Other'], dtype=object)

In [291]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(X_nomiss1)
age_data=le.transform(X_nomiss1)
le.inverse_transform([0,1])

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array(['No', 'Yes'], dtype=object)

In [235]:
age_data

array([0, 0, 1, ..., 0, 0, 0])

In [289]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(X_nomiss2)
gender_data=le.transform(X_nomiss2)
le.inverse_transform([0,1])

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array(['female', 'male'], dtype=object)

In [237]:
type(gender_data)

numpy.ndarray

In [238]:
import pandas as pd
X_age=pd.DataFrame(age_data, columns = ['age_60_and_above'])
X_gender=pd.DataFrame(gender_data, columns = ['gender'])
X_testind=pd.DataFrame(testind_data, columns = ['test_indication'])

In [239]:
X_nomiss

cough  fever  sore_throat  shortness_of_breath  head_ache
0            0      0            0                    0          0
1            0      1            0                    0          0
2            0      0            0                    0          0
3            0      0            0                    0          0
4            0      1            0                    0          0
...        ...    ...          ...                  ...        ...
2742591      0      0            0                    0          0
2742592      0      0            0                    0          0
2742593      0      0            0                    0          0
2742594      0      0            0                    0          0
2742595      0      1            0                    0          0

[2742596 rows x 5 columns]

In [240]:
X1=pd.concat([X_nomiss,X_age,X_gender,X_testind],axis=1)

In [241]:
X1

cough  fever  sore_throat  ...  age_60_and_above  gender  test_indication
0            0      0            0  ...                 0       1                2
1            0      1            0  ...                 0       1                2
2            0      0            0  ...                 1       0                2
3            0      0            0  ...                 0       1                2
4            0      1            0  ...                 0       1                1
...        ...    ...          ...  ...               ...     ...              ...
2742591      0      0            0  ...                 0       0                2
2742592      0      0            0  ...                 0       0                2
2742593      0      0            0  ...                 0       1                2
2742594      0      0            0  ...                 0       0                2
2742595      0      1            0  ...                 0       1                2

[2742596 rows x 8 columns]

In [287]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(y)
y_num=le.transform(y)
le.inverse_transform([0,1,2])

array(['negative', 'other', 'positive'], dtype=object)

In [243]:
len(y1)

2742596

In [244]:
y1=pd.DataFrame(y_num, columns = ['corona_result']).to_numpy()

In [245]:
X1=X1.to_numpy()

In [256]:
X1[0]

array([0, 0, 0, 0, 0, 0, 1, 2])

In [247]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.3, random_state=42)

In [248]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state=0)

model.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

In [249]:
y_pred = model.predict(X_test)

In [250]:
type(y_pred)

numpy.ndarray

In [251]:
#y_test1=y_test['corona_result'].to_numpy()

In [252]:
y_test1

array([0, 0, 0, ..., 0, 0, 0])

In [253]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

print("Accuracy: {}".format(accuracy_score(y_test1, y_pred)))
cf = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)

Accuracy: 0.9087324785878104


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [254]:
print(cr)

              precision    recall  f1-score   support

           0       0.92      0.98      0.95    744644
           1       0.00      0.00      0.00     12169
           2       0.54      0.26      0.35     65966

    accuracy                           0.91    822779
   macro avg       0.49      0.42      0.44    822779
weighted avg       0.88      0.91      0.89    822779



In [281]:
a=[[1, 0, 1, 1, 0, 0, 1, 0]]
#a.reshape(1, -1)
i=model.predict(a)

In [280]:
from sklearn import preprocessing
>>> le = preprocessing.LabelEncoder()
>>> le.fit(y)
le.inverse_transform(i)

array(['positive'], dtype=object)